
- name: Create Azure Deploy
  hosts: localhost
  connection: local
  tasks:
  - azure_rm_deployment:
      state: present
      resource_group_name: arm-tmp-ko
      template_link: 'https://raw.githubusercontent.com/Kaustubhin/azure-test/master/createforest.json'
      parameters_link: 'https://raw.githubusercontent.com/Kaustubhin/azure-test/master/parameters.json'

